language: c
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16"
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-1.8.8-linux64.tar.xz
  - tar xf arduino-1.8.8-linux64.tar.xz
  - sudo mv arduino-1.8.8 /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
install:
  - ln -s $PWD /usr/local/share/arduino/libraries/Minecraft_Link
script:
  - arduino --verify --board arduino:avr:uno $PWD/examples/BareMinimum/BareMinimum.ino
  - arduino --verify --board arduino:avr:uno $PWD/examples/BareMinimum2/BareMinimum2.ino
  - arduino --verify --board arduino:avr:uno $PWD/examples/CustomMessages/CustomMessages.ino
  - arduino --verify --board arduino:avr:mega:cpu=atmega2560 $PWD/examples/CustomSerialPort/CustomSerialPort.ino
